export const SET_HOME_FIELD = 'SET_HOME_FIELDS';
export const CLEAR_HOME_FIELDS = 'CLEAR_HOME_FIELDS';

export const SET_TIMELINE_FIELD = 'SET_TIMELINE_FIELDS';
export const CLEAR_TIMELINE_FIELDS = 'CLEAR_TIMELINE_FIELDS';
